import java.util.Base64

plugins {
  alias(libs.plugins.kotlin.multiplatform)
  alias(libs.plugins.dokka)
  id("config-site")
  id("config-multi-deploy")
}

description = "A Kotlin Multiplatform library for downloading podcast episodes and cutting the injected ads out of them."
version = self.versions.name.get()
group = "com.episode6.tacita"

tasks.wrapper {
  gradleVersion = libs.versions.gradle.core.get()
  distributionType = Wrapper.DistributionType.ALL
}

// Embeds the mp3 test fixtures as base64 in generated commonTest code, so tests run on
// native targets too (kotlin/native test binaries have no classpath resources).
val generateTestFixtures by tasks.registering {
  val fixturesDir = layout.projectDirectory.dir("src/commonTest/resources/audio")
  val outputDir = layout.buildDirectory.dir("generated/testFixtures")
  inputs.dir(fixturesDir)
  outputs.dir(outputDir)
  doLast {
    val fixtures = fixturesDir.asFile.listFiles().orEmpty().sortedBy { it.name }
    val entries = fixtures.joinToString(",\n") { file ->
      // chunked: a single string constant would exceed the jvm's 64KB constant-pool limit
      val chunks = Base64.getEncoder().encodeToString(file.readBytes()).chunked(40_000)
      "  \"${file.name}\" to listOf(\n${chunks.joinToString(",\n") { "    \"$it\"" }},\n  )"
    }
    val outFile = outputDir.get().file("com/episode6/tacita/audio/TestFixtures.kt").asFile
    outFile.parentFile.mkdirs()
    outFile.writeText(
      """
      |// Generated by the generateTestFixtures gradle task from src/commonTest/resources/audio — do not edit.
      |package com.episode6.tacita.audio
      |
      |import kotlin.io.encoding.Base64
      |
      |internal fun fixture(name: String): ByteArray =
      |  Base64.decode(checkNotNull(fixtureData[name]) { "missing test fixture audio/${'$'}name" }.joinToString(""))
      |
      |private val fixtureData: Map<String, List<String>> = mapOf(
      |$entries,
      |)
      |""".trimMargin()
    )
  }
}

kotlin {
  sourceSets {
    val commonMain by getting {
      dependencies {
        api(libs.ktor.client.core)
        api(libs.okio.core)
        implementation(libs.kotlinx.coroutines.core)
      }
    }
    val commonTest by getting {
      kotlin.srcDir(generateTestFixtures)
      dependencies {
        implementation(libs.ktor.client.mock)
        implementation(libs.kotlinx.coroutines.test)
      }
    }
    // by-name matching instead of `by getting` so CI shards that skip the jvm target still configure
    matching { it.name == "jvmMain" }.configureEach {
      dependencies {
        implementation(libs.ktor.client.okhttp)
      }
    }
    matching { it.name == "jvmTest" }.configureEach {
      dependencies {
        // jlayer: independent reference decoder for Mp3Decoder verification
        implementation(libs.jlayer.core)
        // jump3r (pure-java LAME port): in-test encoder for acoustic-fingerprint
        // cross-encode fixtures (same tool that generated stereo.mp3)
        implementation(libs.jump3r.core)
      }
    }
  }
}
